language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --write-mode=diff
  - cargo build --verbose --all
  - cargo test --verbose --all
after_script:
  - bash -euo pipefail .mpl-check.sh
