language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - if [[ "${TRAVIS_RUST_VERSION}" = "stable" ]]; then rustup component add rustfmt-preview; cargo fmt --all -- --check; fi
  - bash -euo pipefail .mpl-check.sh
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
